# Generated by Django 3.2.12 on 2022-05-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genres'),
        ('community', '0002_rename_comment_advertisementcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='movies.movie'),
            preserve_default=False,
        ),
    ]
