# Generated by Django 3.2.12 on 2022-05-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_advertisement_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
