# Generated by Django 3.2.12 on 2022-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220521_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='general_or_seller',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='blog_url',
            field=models.URLField(blank=True, max_length=60, null=True),
        ),
    ]
