# Generated by Django 3.2.12 on 2022-05-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220521_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='general_or_seller',
            new_name='isgeneral',
        ),
    ]
