# Generated by Django 3.2.12 on 2022-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_general_or_seller_user_isgeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isgeneral',
            field=models.CharField(max_length=10),
        ),
    ]
