# Generated by Django 3.2.12 on 2022-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='rating',
            field=models.CharField(choices=[('5', '★★★★★'), ('4', '★★★★'), ('3', '★★★'), ('2', '★★'), ('1', '★'), (None, '선택')], max_length=10),
        ),
    ]
