# Generated by Django 3.2.12 on 2022-05-23 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wish_users',
            field=models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
